# ------------------
# Travis CI settings
# ------------------
# Test changes of this .travis.yml config before submitting them:
# https://lint.travis-ci.org
# ---------------------------------------------------------------

language: java
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_script:
  - npm install -g grunt-cli bower
  - gem install sass
