# ------------------
# Travis CI settings
# ------------------
# Test changes of this .travis.yml config before submitting them:
# https://lint.travis-ci.org
# ---------------------------------------------------------------

language: java
jdk: oraclejdk8
script: mvn clean package
before_script:
  - npm install -g bower
