spring:
  jpa:
    show_sql: false
    defer-datasource-initialization: true
  sql.init:
    platform: h2
    mode: always
  mail:
    host:
    port: 25
    username:
    password:
    protocol: smtp
    tls: false
    senderHost:

logging.level.de.meonwax.predictr: DEBUG

server:
  error.whitelabel.enabled: false
  port: 8080
  forward-headers-strategy: native
predictr:
  rememberMeKey: 7f4a2c3d1e0b7a8c9d0f1f2b3b4c7d6e9f8a9b0c # 20 byte random key
  # Uncomment any pages to hide them in the navigation
  pagesBlacklist:
#    - bets
#    - ladder
#    - questions
#    - rules
#    - shoutbox
#    - settings
---

server:
  address: 0.0.0.0 # Mandatory to be accessible within a Docker container
  forward-headers-strategy: native

spring:
  config.activate.on-profile: production
  jpa.hibernate.ddl-auto: update
  sql.init:
    platform: mysql
    mode: never
  datasource:
    url: jdbc:mysql://localhost/predictr?autoReconnect=true&useSSL=false
    username: predictr
    password: 123vorbei

logging.level.de.meonwax.predictr: INFO
