spring:
    jpa.show_sql: false
    datasource.platform: h2

server:
    error.whitelabel.enabled: false
    port: 8081

predictr:
    owner: John Doe
    title: Predictr
    version: 0.0.1
    adminEmail: admin@example.com
    registrationEnabled: true
    points:
        result: 5
        tendency: 2
        tendencySpread: 3
---

spring:
    profiles: production
    datasource.platform: mysql
    jpa.hibernate.ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost/predictr
        username: predictr
        password: 123vorbei

server:
    port: 8090
