spring:
    jpa.show_sql: false
    datasource.platform: h2
    mail:
        host:
        port: 25
        username:
        password:
        protocol: smtp
        tls: false

logging.level.de.meonwax.predictr: DEBUG

server:
    error.whitelabel.enabled: false
    port: 8081
    address: 127.0.0.1

predictr:
    owner: John Doe
    title: Predictr
    version: 4.2.2
    rememberMeKey: 8604aa56a02e3dc7b191859ef5952fe49fd1f128
    adminEmail: admin@example.com
    showImportantMessage: true
    # Uncomment any pages to hide them in the navigation
    pagesBlacklist:
        #- bets
        #- ladder
        #- questions
        #- rules
        #- shoutbox
        #- settings
    points:
        result: 5
        tendency: 2
        tendencySpread: 3
---

spring:
    profiles: production
    jpa.hibernate.ddl-auto: update
    datasource:
        platform: mysql
        test-on-borrow: true
        validationQuery: SELECT 1
        url: jdbc:mysql://localhost/predictr
        username: predictr
        password: 123vorbei

logging.level.de.meonwax.predictr: INFO

server:
    port: 8080
    use-forward-headers: true
