spring:
    jpa.show_sql: false
    datasource.platform: h2

logging.level.de.meonwax.predictr: DEBUG

server:
    error.whitelabel.enabled: false
    port: 8081
    address: 127.0.0.1

predictr:
    owner: John Doe
    title: Predictr
    version: 0.0.1
    adminEmail: admin@example.com
    registrationEnabled: true
    points:
        result: 5
        tendency: 2
        tendencySpread: 3
---

spring:
    profiles: production
    datasource.platform: mysql
    jpa.hibernate.ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost/predictr
        username: predictr
        password: 123vorbei

logging.level.de.meonwax.predictr: INFO

server.port: 8080
