spring.jpa.show_sql: true

server.port: 8081

predictr:
    author: John Doe
    title: Predictr
    version: 0.0.1
    adminEmail: admin@example.com
    registrationEnabled: true
    points:
        result: 5
        tendency: 2
        tendencySpread: 3